name: Java CI/CD with Maven and Docker
on:
  pull_request:
    branches:
      - '**'  # Runs when a PR is created
  push:
    branches:
      - main  # Runs after a PR is merged to master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Run Tests
        run: mvn test
      - name: Install Dependencies (Skipping Tests)
        run: mvn install -DskipTests
      - name: Build Docker Image
        run: docker build -t employeemanagementsystem:v0.1 .
